### ISSUE TITLE
Empty URi

### ISSUE THREAD

**Issue by princeydev** [szepeviktor/github-link#6]
Hello,
Thanks for this plugin, it's a great addition to github-updater.
I had this issue: the link to the bitbucket plugin URi was empty. In order to make it work i had to change $plugin_data["Bitbucket URI"] to $plugin_data["Bitbucket Plugin URI"] in github-link.php, line 95.

**Comment by szepeviktor** [comment]
Thank you very much!

**Comment by princeydev** [comment]
No worries, thank _you_ for this plugin ;)
