### ISSUE TITLE
Icon Size in WordPress 4.9

### ISSUE THREAD

**Issue by thefrosty** [szepeviktor/github-link#8]
Looks like there has been a little refactor to the layout and sizes on the plugins page in WordPress 4.9 that's broken the dashicon layout.

![screenshot-2017-11-22 plugins frosty media plugins wordpress](https://user-images.githubusercontent.com/367897/33133909-1b6c2b14-cf53-11e7-9470-99ce1882c9e7.png)

**Comment by szepeviktor** [comment]
Some how core defines 64×64 dimensions.

**Comment by thefrosty** [comment]
I think the new dimensions are for the updated upgrade plugin screen, where icons are now present next the the plugin in question getting upgraded.

Great quick fix! 👍

**Comment by szepeviktor** [comment]
I see you are making an effort to [secure wp-admin](https://en.wikipedia.org/wiki/Security_through_obscurity).
Try https://github.com/szepeviktor/wordpress-fail2ban

**Comment by thefrosty** [comment]
@szepeviktor Just an FYI, 0cf351a407d3f9bab6a00a33585f063f68c399bd didn't fix the issue since it's targeted on the `:before` pseudo element.

```php
// Might need to add a hook for the network admin as-well.
add_action( 'admin_head-plugins.php', [ $this, 'github_link_css_fix' ] );
/**
 * Fixes the large icons found in WordPress > 4.9.
 */
public function github_link_css_fix() {
    global $wp_version;

    if ( version_compare( $wp_version, '4.9', '>=' ) ) {
        ?>
        <style type="text/css">
            .plugins .plugin-title .github-link.dashicons::before {
                background-color: transparent;
                box-shadow: none;
                font-size: 16px;
                color: inherit;
            }
        </style>
        <?php
    }
}
```
```php
$wp_link_template = '<a href="%s" title="%s" target="_blank"><span style="width: 16px; height: 16px; color:#2880A8; font-size:18px; vertical-align:-3px;" class="github-link dashicons dashicons-wordpress"></span></a>';
```

**Comment by szepeviktor** [comment]
Would you accept write permission on this repo?

(as I'm not a GHU user)

**Comment by thefrosty** [comment]
Sure.

**Comment by szepeviktor** [comment]
Please try to follow WPCS. Thanks!
